# Generated by Django 4.2.1 on 2023-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=50)),
                ("Subject", models.CharField(max_length=100, null=True)),
                ("Message", models.TextField()),
                ("Timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
